export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_ERROR = 'FETCH_ORDERS_ERROR';
export const FETCH_ORDERS_PENDING = 'FETCH_ORDERS_PENDING';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';