export const FETCH_API_DRINKS = 'FETCH_API_DRINKS';
export const FETCH_API_DRINKS_ERROR = 'FETCH_API_DRINKS_ERROR';
export const FETCH_API_DRINKS_PENDING = 'FETCH_API_DRINKS_PENDING';
export const DRINK_SELECTED = 'DRINK_SELECTED';