export const FETCH_API_VOUCHER = 'FETCH_API_VOUCHER';
export const FETCH_API_VOUCHER_ERROR = 'FETCH_API_VOUCHER_ERROR';
export const FETCH_API_VOUCHER_PENDING = 'FETCH_API_VOUCHER_PENDING';
export const VOUCHER_ID_INPUT = 'VOUCHER_ID_INPUT';

